/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "counter.h"
static int result;

int *down_1_svc(int *argp, struct svc_req *rqstp) {
  result += *argp;
  return &result;
}

int *up_1_svc(int *argp, struct svc_req *rqstp) {
  result -= *argp;
  return &result;
}
