/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COUNTER_H_RPCGEN
#define _COUNTER_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif

#define COUNTER 0x20151782
#define V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define down 1
extern int *down_1(int *, CLIENT *);
extern int *down_1_svc(int *, struct svc_req *);
#define up 2
extern int *up_1(int *, CLIENT *);
extern int *up_1_svc(int *, struct svc_req *);
extern int counter_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define down 1
extern int *down_1();
extern int *down_1_svc();
#define up 2
extern int *up_1();
extern int *up_1_svc();
extern int counter_1_freeresult();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COUNTER_H_RPCGEN */
