/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "counter.h"
#include <memory.h> /* for memset */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = {25, 0};

int *down_1(int *argp, CLIENT *clnt) {
  static int clnt_res;

  memset((char *)&clnt_res, 0, sizeof(clnt_res));
  if (clnt_call(clnt, down, (xdrproc_t)xdr_int, (caddr_t)argp,
                (xdrproc_t)xdr_int, (caddr_t)&clnt_res,
                TIMEOUT) != RPC_SUCCESS) {
    return (NULL);
  }
  return (&clnt_res);
}

int *up_1(int *argp, CLIENT *clnt) {
  static int clnt_res;

  memset((char *)&clnt_res, 0, sizeof(clnt_res));
  if (clnt_call(clnt, up, (xdrproc_t)xdr_int, (caddr_t)argp, (xdrproc_t)xdr_int,
                (caddr_t)&clnt_res, TIMEOUT) != RPC_SUCCESS) {
    return (NULL);
  }
  return (&clnt_res);
}
