// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: counter.proto
#ifndef GRPC_counter_2eproto__INCLUDED
#define GRPC_counter_2eproto__INCLUDED

#include "counter.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

class CounterService final {
 public:
  static constexpr char const* service_full_name() {
    return "CounterService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status up(::grpc::ClientContext* context, const ::Counter& request, ::Counter* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Counter>> Asyncup(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Counter>>(AsyncupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Counter>> PrepareAsyncup(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Counter>>(PrepareAsyncupRaw(context, request, cq));
    }
    virtual ::grpc::Status down(::grpc::ClientContext* context, const ::Counter& request, ::Counter* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Counter>> Asyncdown(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Counter>>(AsyncdownRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Counter>> PrepareAsyncdown(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Counter>>(PrepareAsyncdownRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void up(::grpc::ClientContext* context, const ::Counter* request, ::Counter* response, std::function<void(::grpc::Status)>) = 0;
      virtual void up(::grpc::ClientContext* context, const ::Counter* request, ::Counter* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void down(::grpc::ClientContext* context, const ::Counter* request, ::Counter* response, std::function<void(::grpc::Status)>) = 0;
      virtual void down(::grpc::ClientContext* context, const ::Counter* request, ::Counter* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Counter>* AsyncupRaw(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Counter>* PrepareAsyncupRaw(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Counter>* AsyncdownRaw(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Counter>* PrepareAsyncdownRaw(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status up(::grpc::ClientContext* context, const ::Counter& request, ::Counter* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Counter>> Asyncup(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Counter>>(AsyncupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Counter>> PrepareAsyncup(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Counter>>(PrepareAsyncupRaw(context, request, cq));
    }
    ::grpc::Status down(::grpc::ClientContext* context, const ::Counter& request, ::Counter* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Counter>> Asyncdown(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Counter>>(AsyncdownRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Counter>> PrepareAsyncdown(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Counter>>(PrepareAsyncdownRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void up(::grpc::ClientContext* context, const ::Counter* request, ::Counter* response, std::function<void(::grpc::Status)>) override;
      void up(::grpc::ClientContext* context, const ::Counter* request, ::Counter* response, ::grpc::ClientUnaryReactor* reactor) override;
      void down(::grpc::ClientContext* context, const ::Counter* request, ::Counter* response, std::function<void(::grpc::Status)>) override;
      void down(::grpc::ClientContext* context, const ::Counter* request, ::Counter* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Counter>* AsyncupRaw(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Counter>* PrepareAsyncupRaw(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Counter>* AsyncdownRaw(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Counter>* PrepareAsyncdownRaw(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_up_;
    const ::grpc::internal::RpcMethod rpcmethod_down_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status up(::grpc::ServerContext* context, const ::Counter* request, ::Counter* response);
    virtual ::grpc::Status down(::grpc::ServerContext* context, const ::Counter* request, ::Counter* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_up : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_up() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_up() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status up(::grpc::ServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestup(::grpc::ServerContext* context, ::Counter* request, ::grpc::ServerAsyncResponseWriter< ::Counter>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_down : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_down() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_down() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status down(::grpc::ServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestdown(::grpc::ServerContext* context, ::Counter* request, ::grpc::ServerAsyncResponseWriter< ::Counter>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_up<WithAsyncMethod_down<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_up : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_up() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Counter, ::Counter>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Counter* request, ::Counter* response) { return this->up(context, request, response); }));}
    void SetMessageAllocatorFor_up(
        ::grpc::MessageAllocator< ::Counter, ::Counter>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Counter, ::Counter>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_up() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status up(::grpc::ServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* up(
      ::grpc::CallbackServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_down : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_down() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::Counter, ::Counter>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Counter* request, ::Counter* response) { return this->down(context, request, response); }));}
    void SetMessageAllocatorFor_down(
        ::grpc::MessageAllocator< ::Counter, ::Counter>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Counter, ::Counter>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_down() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status down(::grpc::ServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* down(
      ::grpc::CallbackServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_up<WithCallbackMethod_down<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_up : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_up() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_up() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status up(::grpc::ServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_down : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_down() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_down() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status down(::grpc::ServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_up : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_up() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_up() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status up(::grpc::ServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestup(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_down : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_down() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_down() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status down(::grpc::ServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestdown(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_up : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_up() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->up(context, request, response); }));
    }
    ~WithRawCallbackMethod_up() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status up(::grpc::ServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* up(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_down : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_down() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->down(context, request, response); }));
    }
    ~WithRawCallbackMethod_down() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status down(::grpc::ServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* down(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_up : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_up() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Counter, ::Counter>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Counter, ::Counter>* streamer) {
                       return this->Streamedup(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_up() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status up(::grpc::ServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedup(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Counter,::Counter>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_down : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_down() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Counter, ::Counter>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Counter, ::Counter>* streamer) {
                       return this->Streameddown(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_down() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status down(::grpc::ServerContext* /*context*/, const ::Counter* /*request*/, ::Counter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streameddown(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Counter,::Counter>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_up<WithStreamedUnaryMethod_down<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_up<WithStreamedUnaryMethod_down<Service > > StreamedService;
};


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_counter_2eproto__INCLUDED
