// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: counter.proto

#include "counter.pb.h"
#include "counter.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* CounterService_method_names[] = {
  "/CounterService/up",
  "/CounterService/down",
};

std::unique_ptr< CounterService::Stub> CounterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CounterService::Stub> stub(new CounterService::Stub(channel, options));
  return stub;
}

CounterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_up_(CounterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_down_(CounterService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CounterService::Stub::up(::grpc::ClientContext* context, const ::Counter& request, ::Counter* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Counter, ::Counter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_up_, context, request, response);
}

void CounterService::Stub::async::up(::grpc::ClientContext* context, const ::Counter* request, ::Counter* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Counter, ::Counter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_up_, context, request, response, std::move(f));
}

void CounterService::Stub::async::up(::grpc::ClientContext* context, const ::Counter* request, ::Counter* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_up_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Counter>* CounterService::Stub::PrepareAsyncupRaw(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Counter, ::Counter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_up_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Counter>* CounterService::Stub::AsyncupRaw(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncupRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CounterService::Stub::down(::grpc::ClientContext* context, const ::Counter& request, ::Counter* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Counter, ::Counter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_down_, context, request, response);
}

void CounterService::Stub::async::down(::grpc::ClientContext* context, const ::Counter* request, ::Counter* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Counter, ::Counter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_down_, context, request, response, std::move(f));
}

void CounterService::Stub::async::down(::grpc::ClientContext* context, const ::Counter* request, ::Counter* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_down_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Counter>* CounterService::Stub::PrepareAsyncdownRaw(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Counter, ::Counter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_down_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Counter>* CounterService::Stub::AsyncdownRaw(::grpc::ClientContext* context, const ::Counter& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdownRaw(context, request, cq);
  result->StartCall();
  return result;
}

CounterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CounterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CounterService::Service, ::Counter, ::Counter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CounterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Counter* req,
             ::Counter* resp) {
               return service->up(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CounterService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CounterService::Service, ::Counter, ::Counter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CounterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Counter* req,
             ::Counter* resp) {
               return service->down(ctx, req, resp);
             }, this)));
}

CounterService::Service::~Service() {
}

::grpc::Status CounterService::Service::up(::grpc::ServerContext* context, const ::Counter* request, ::Counter* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CounterService::Service::down(::grpc::ServerContext* context, const ::Counter* request, ::Counter* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


