hand_over_hand: hand_over_hand.c
	gcc -g -o $@ $<

no_hand_over_hand: no_hand_over_hand.c
	gcc -g -o $@ $<

read_write_lock: read_write_lock.cpp
	g++ -g -o $@ $<

clean:
	rm -f hand_over_hand no_hand_over_hand read_write_lock
