mac: mac.c
	gcc mac.c -o mac

if_state: if_state.c
	gcc if_state.c -o if_state

mac_proxy: mac_proxy.c
	gcc mac_proxy.c -o mac_proxy

bpf_dns: bpf_dns.c
	gcc bpf_dns.c -o bpf_dns

packet_count: packet_count.c
	gcc packet_count.c -o packet_count

arping: arping.c
	gcc arping.c -o arping

change_route: change_route.c
	gcc change_route.c -o change_route
